import Head from "next/head";
import Image from "next/image";
import {
  Slider,
  Grid,
  Skeleton,
  Container,
  TextInput,
  Button,
} from "@mantine/core";

import loginFlow from "../public/images/login.jpeg";
import cultLogo from "../public/images/logo.png";

export default function Home() {
  const child = <Skeleton height={140} radius="md" animate={false} />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container my="md">
        <Grid>
          <Grid.Col xs={4} style={{ alignItems: "center" }}>
            <Image src={cultLogo} alt="login flow" width={200}></Image>
          </Grid.Col>

          <Grid.Col xs={8}>
            <TextInput
              // label="Input label"
              // description="Input description"
              autoComplete="tel-national"
            />
          </Grid.Col>

          <Grid.Col xs={8}>
            <Button fullWidth color="gray">CONTINUE</Button>
          </Grid.Col>

          <Grid.Col xs={4}>
            <Image src={loginFlow} alt="login flow" width={200}></Image>
          </Grid.Col>

          <Grid.Col xs={8}>{child}</Grid.Col>
          <Grid.Col xs={4}>{child}</Grid.Col>
          <Grid.Col xs={3}>{child}</Grid.Col>
          <Grid.Col xs={3}>{child}</Grid.Col>
          <Grid.Col xs={6}>
            <Slider defaultValue={40} min={10} max={90} />
          </Grid.Col>
        </Grid>
      </Container>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
